# pou le developpemnt   
# docker-compose up -d  pour lancer les containers... l'application est accessiblepar defaut à  memo.localhost
# modifier le Caddyfile pour changer le nom de domaine

# la configuration suivante est pour le mmode developpement
services:
  lb:
    image: caddy
    hostname: lb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  
# le container memo_db est un container postgresql
# il contient la structure de la base de donnée  et juste un petit jeu de données pour l'exemple
  memo_db:
    image: damiend0cker/memo_db:latest
    restart: on-failure
    container_name: memo_db
    volumes:
      - memo_db_data:/var/lib/postgresql/data
    
  


  memo_app:
    image: damiend0cker/memo_svelte:dev
    container_name: front
    hostname: front
    working_dir: /app
    volumes:
    # à modifier selon votre arborescence
      - ../memo-sveltkit:/app  
    restart: on-failure
    ports:
      - 3333:3333
    depends_on:
      - memo_db
    environment:
      DATABASE_URL: postgres://memo:memo@memo_db:5432/memo?sslmode=disable
volumes:
  memo_db_data:






