
# docker-compose -f docker-compose-prod.yml up -d  pour lancer les containers... 

# la configuration suivante est pour le mmode production
services:

  lb:
    image: caddy
    hostname: lb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  
# le container memo_db est un container postgresql
# il contient la structure de la base de donnée  et un jeu de données pour l'exemple
  memo_db:
    image: damiend0cker/memo_db:latest
    restart: on-failure
    container_name: memo_db
    volumes:
      - memo_db_data:/var/lib/postgresql/data



# une partie du code s'execute coté serveur et une partie coté client
  memo_app:
    image: damiend0cker/memo_svelte:latest
    hostname: front
    restart: on-failure
    depends_on:
      - memo_db
    environment:
          DATABASE_URL: postgres://memo:memo@memo_db:5432/memo?sslmode=disable



volumes:
  memo_db_data:






