
# docker-compose -f docker-compose-prod.yml up -d  pour lancer les containers... l'application est accessible 127.0.0.1

# le server apache permet de faire la resolution dns des nom des containers pour les requetes http vers le back 
# la configuration suivante est pour le mmode production
services:

  lb:
    image: caddy
    hostname: lb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  
# le container memo_db est un container postgresql
# il contient la structure de la base de donnée  et juste un petit jeu de données pour l'exemple
  memo_db:
    image: damiend0cker/memo_db:v.1.0.5
    container_name: memo_db
    volumes:
      - memo_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5433:5432

# le container memo_back est un container NodeJs 
  memo_back:
    image: damiend0cker/memo_back:v.1.0.8
    container_name: memo_back
    hostname: memo_back
    restart: always
    # ports:
    #   - 3001:3001
    environment:
      DATABASE_URL: postgres://memo:memo@memo_db:5432/memo?sslmode=disable
    depends_on:
      - memo_db
      
# le container memo_svelte est un container sveltkit  il contient le front de l'application 
# une partie du code s'execute coté serveur et une partie coté client
  memo_svelte:
    image: damiend0cker/memo_svelte:v.1.0.3
    container_name: front
    restart: always
    hostname: front
    depends_on:
      - memo_back
      - memo_db
    # ports:
    #   - 3000:5173

volumes:
  memo_db_data:






