FROM httpd:latest



# permet de copier le fichier de configuration dans le conteneur
# modifiction de ce fichier pour ajouter : IncludeOptional conf/sites/*.conf
# qui permet de charger les fichiers de configuration des sites
COPY httpd.conf /usr/local/apache2/conf/httpd.conf


# création du dossier qui contiendra les fichiers de configuration des sites

RUN mkdir -p /usr/local/apache2/conf/sites/

# copie du fichier de configuration du site dans le dossier créé
COPY ./reverse-proxy.conf   /usr/local/apache2/conf/sites/

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]


