- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart HAProxy


- name: Start HAProxy if not started
  ansible.builtin.systemd_service:
    name: haproxy
    state: started
    enabled: yes